### ISSUE TITLE
Incorrect CPU Tempreature Display in SPEEDX Application

### ISSUE THREAD

**Issue by jckso** [rishabh3354/SPEEDX#1]
# Incorrect CPU Temperature Display in SPEEDX Application

## Description
The SPEEDX application displays incorrect real-time CPU temperature values. The temperature shown is significantly higher than the actual readings from the system's native monitoring tools.

## Steps to Reproduce
1. Open the SPEEDX application.
2. Navigate to the "CPU Usage" section.
3. Observe the CPU temperature displayed in the application.

## Expected Behavior
The CPU temperature should match the readings provided by the system's native monitoring tools or utilities such as `screenfetch` (on Linux).

**Expected temperature: 27 C**

### Screenfetch Image
![ScreenfetchCPU](https://github.com/user-attachments/assets/a6f1582e-a6a2-441b-9ec7-2c4ee2c39860)

## Observed Behavior
The temperature displayed in the SPEEDX application does not match the actual temperature reported by other tools.

**Observed tempreature: 52 C**

### SPEEDX image

![speedxCPU](https://github.com/user-attachments/assets/f4cff2c6-c59a-4473-a77d-47d56ebefcc8)

## Environment
- **Operating System:** Ubuntu 24.04 LTS 
- **Application Version:** 0.2 (Snap Package)

**Comment by jckso** [comment]
This issue has focused on CPU's incorrect temperature showing

**Comment by rishabh3354** [comment]
Did you give hardware permission to your snap app: speedx?

If not , then give it using the cmd below:

`sudo snap connect speedx:hardware-observe

`
As mentioned in the app description here: 
(Note#2)
https://snapcraft.io/speedx

**Comment by jckso** [comment]
After granting `hardware-observe` permission using the command `sudo snap connect speedx:hardware-observe`, the CPU temperature is now displayed correctly. However, two issues persist:

1. **Incorrect RAM Usage:** The application shows a significantly mismatched RAM usage compared to real-time system statistics.
2. **Static CPU Temperature:** The CPU temperature does not update dynamically in real-time, unlike other metrics such as CPU load and network speed.

To provide more clarity, I have attached a screen recording demonstrating these issues. In the video, you can observe:

- The mismatch in RAM usage between the application and the actual system metrics.
- The static nature of the CPU temperature display, which does not change even when system conditions clearly fluctuate.

[issues_markdown.webm](https://github.com/user-attachments/assets/62893539-7d7b-45b3-bba1-71b9f4d274e2)


Please review the video for further insights into the problem.
